basePath: /
definitions:
  models.ResponseUser:
    properties:
      email:
        type: string
      name:
        type: string
    required:
    - email
    - name
    type: object
  utils.Response:
    properties:
      errors: {}
      message:
        type: string
      pageInfo: {}
      results: {}
      success:
        type: boolean
    type: object
info:
  contact: {}
  description: CRUD Swagger
  title: CRUD
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: List all users
      produces:
      - application/json
      responses:
        "200":
          description: string
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      tags:
      - users
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Create new user
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: name
        required: true
        type: string
      - in: formData
        name: password
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ResponseUser'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      tags:
      - createuser
  /users/{id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: Delete user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      tags:
      - delete
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Get detail user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ResponseUser'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      tags:
      - user
    patch:
      consumes:
      - application/x-www-form-urlencoded
      description: Update user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: name
        required: true
        type: string
      - in: formData
        name: password
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ResponseUser'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      tags:
      - update
  /users/sort:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: List all users
      produces:
      - application/json
      responses:
        "200":
          description: string
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Response'
      tags:
      - users
swagger: "2.0"
