name: Push Backend CRUD APP to GHCR
run-name: Release Image GHCR
on: [push]
jobs:
  push-image-to-ghcr:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4 
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          username: ${{ secrets.REMOTE_USER }}
          host: ${{ secrets.REMOTE_HOST }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ghcr.io/${{ github.repository }}
            cd ~
            cd fgo24/be-crud
            docker-compose up -d